BrefKernel return types
brefphp/symfony-bridge pull request #47
Opened 2021-11-20 16:24 UTC by amacrobert

Fixes #46

2021-11-20 18:08 UTC, t-richard commented
Note that this is a breaking change.

2021-11-20 21:07 UTC, amacrobert commented
Should I address the PHPCS failure, even though it's from code not in my PR?

2021-12-07 22:10 UTC, chekalsky commented
@mnapoli any plans on merging this? AFAIK those deprecations are critical in order to use Symfony 6?

2021-12-13 09:16 UTC, mnapoli commented
How can we solve the breaking change?

Is it a matter of upgrading the Symfony dependency? Is so, what would be the new range?

2021-12-13 09:55 UTC, t-richard commented
Actually I think this just needs a new minor tag because of the BC break. 

Defining a return type on a child method where a parent does not define one is allowed (covariance of return types) which means we can still support older versions of Symfony.

So it would require to
[x] Add types where needed
[ ] Allow `symfony/http-kernel:^6.0` and `symfony/filesystem:^6.0` (fixes #49)
[ ] Update the CI to run tests on newer PHP & Symfony versions
[ ] Merge into master and tag version `0.2.0`

This way we remove deprecation notices for Symfony 5.4, are compatible with Symfony 6.0 and ensure PHP 8.1 compatibility.

We may want to split into multiple PRs but I think it would make sense to do all of this before tagging `0.2.0`.

Does that make sense?

2021-12-13 18:06 UTC, mnapoli commented
Sounds good to me

2021-12-20 03:31 UTC, amacrobert commented
Alright I updated composer dependencies, and added latest PHP and Symfony versions to the tests. Awaiting workflow approval.

2021-12-20 06:56 UTC, t-richard approved these changes
Seems good, let's just wait for the tests to run.

2021-12-20 12:54 UTC, t-richard requested changes
Tests are failing on 6.0 because Bref is a dependency of this bridge and is not yet compatible because of Silly (see https://github.com/brefphp/bref/pull/1117)

2021-12-20 12:54 UTC, t-richard commented on .github/workflows/ci.yml
> +        sf_version: ['4.4.*', '5.0.*', '5.2.*', '5.4.*', '6.0.*']
Symfony 6 is compatible with php >= 8.0 so running tests on 7.3 and 7.4 will always fail

```suggestion
        sf_version: ['4.4.*', '5.0.*', '5.2.*', '5.4.*', '6.0.*']
        exclude:
          - php: 7.3
            sf_version: 6.0.*
            
          - php: 7.4
            sf_version: 6.0.*
```

2021-12-28 11:05 UTC, merged

2021-12-28 11:05 UTC, mnapoli commented
Thanks, merged via #50!