allow to use custom runtime
brefphp/symfony-bridge pull request #57
Opened 2022-02-12 17:29 UTC by allan-simon

close #56

2022-02-13 23:26 UTC, allan-simon commented
now it should be good @mnapoli

2022-05-13 13:48 UTC, DaMitchell commented
Is there anything stopping this from being added?

2022-05-13 13:52 UTC, mnapoli commented
@DaMitchell what would be your use case?

2022-05-15 17:50 UTC, mnapoli commented
Got it. Is it something that could be implemented in `Kernel::boot()` or a similar method?

Is there any reason to implement it in a custom runtime? (I'm trying to be exhaustive and figure out if this is really something worth the maintenance effort)

2022-05-15 19:17 UTC, allan-simon commented
in my case it was because the `env` and `debug` attribute used to construct the kernel were overwritten by the dotenv value , and so `Kernel::boot` is already too late

2022-05-16 06:00 UTC, t-richard commented
@allan-simon maybe it didn't worded in boot because of something similar to what I found in this PR https://github.com/brefphp/symfony-bridge/pull/37

That said, adding support for any runtime is out of the scope of this bridge for now. 

I fear that if we support that, we end up with people wanting to use runtimes for roadrunner, reactphp or swoole in Lambda for example and that may not work as expected in a Lambda environment.

That being said, if that's a real blocker, we could allow to specify a runtime but only if it's an instance of SymfonyRuntime. 

That way we support use cases like yours but constrain it to something we know works and that we can maintain.

2022-05-16 06:55 UTC, allan-simon commented
@t-richard  I've checked, and I think here it was not the issue, but if I remember my investigation (i'ts been a while so I may recall incorrectly) it was really a "by design" , as the Kernel constructor already expect to receive env variables , which mean they need to be ready by the time you instantiate it.

I understand that opening to any kind of custom runtime may widen too much the scope and make it unbearable to support in term of human time,  so your proposition of limiting it to sub-class of SymfonyRuntime sounds like a good compromise to me.

2024-08-27 05:35 UTC, Nyholm approved these changes
I appreciate this.

2024-08-27 07:55 UTC, mnapoli requested changes
Thanks, to piggy-back on the comments above let's merge this with a check that the runtime extends `SymfonyRuntime`

2024-08-27 09:07 UTC, allan-simon commented
sure no problem

2024-08-27 09:15 UTC, allan-simon commented on src/HandlerResolver.php
> +            $runtime = new $runtimeClass($options);
```suggestion
            $runtime = new $runtimeClass($options);
            if (!$runtime instanceof \Symfony\Component\Runtime\SymfonyRuntime) {
                throw new \RuntimeException("The runtime class '$runtimeClass' must extend Symfony\Component\Runtime\SymfonyRuntime.");
            }
}
```

2024-08-27 09:17 UTC, allan-simon commented
@mnapoli  done, I've tested locally by monkeypatching my vendor

2024-08-27 12:32 UTC, mnapoli approved these changes

2024-08-27 12:49 UTC, Nyholm commented
I've rebased the PR and fixed the CI issues

2024-08-27 12:52 UTC, Nyholm approved these changes

2024-08-27 12:55 UTC, merged